### ISSUE TITLE
#9 Breaks marking of isearch regexp

### ISSUE THREAD

**Issue by bscuron** [corytertel/macrursors#10]
`macrursors-mark-from-isearch`, `macrursors-mark-next-from-isearch`, and `macrursors-mark-previous-from-isearch` are currently broken if the isearch string is a regexp. This is because of the PR that is currently merged #9. At the time of creating the PR, I did not realize this would break the isearch functions.

Current behavior:

https://user-images.githubusercontent.com/29784485/221420109-b1a6ebbc-e0f5-4207-885c-f40c5c153e64.mov

Desired behavior (with #9 reverted):

https://user-images.githubusercontent.com/29784485/221420122-9d1f18dd-9244-4bdd-ba57-345ae40a4542.mov

Reverting #9 should fix this problem. However, it would then reintroduce the problem where if a region is selected, any characters in the region will be treated as a regexp instead of a regular string. It may be possible to have different behavior depending on if the region is activated, but I am not sure if it is a great idea. @karthink What do you think?

**Comment by karthink** [comment]
It shouldn't be doing a regexp search when a region is selected. Could you try editing `macrursors--instance-with-bounds` to return the regexp-quoted region?

This involves changing the cond clause
```emacs-lisp
((use-region-p)
    (when (< (point) (mark))
      (exchange-point-and-mark))
    (list (buffer-substring-no-properties
           (region-beginning) (region-end))
          (region-beginning)
          (region-end)))
```
to
```emacs-lisp
((use-region-p)
    (when (< (point) (mark))
      (exchange-point-and-mark))
    (list (regexp-quote
           (buffer-substring-no-properties
            (region-beginning) (region-end)))
          (region-beginning)
          (region-end)))
```

the marking functions (`macrursors--mark-all-instances-of` etc) should not use regexp-quote, as they will break marking symbols too, not just isearch.

**Comment by bscuron** [comment]
Pre #9, this was the current behavior of `macrursors-mark-next-instance-of`. It seems like it is not treating the `**` string as plain text. Here is a video:

https://user-images.githubusercontent.com/29784485/221432095-67403ada-d19b-4728-a538-6e560d72a92e.mov

With your suggested fix, both marking a string like `**` and marking an isearch regexp work as intended. Here is a video:

https://user-images.githubusercontent.com/29784485/221432282-2cca92d4-47e2-437a-bdc7-c3babd9b8c08.mov

Thank you a lot for the help! Do you want to submit the new PR, I don't want to take credit @karthink?

**Comment by karthink** [comment]
Could you test to ensure that marking symbols works as intended too? (for example with `macrursors-mark-next-instance-of` with point on a symbol)

> Do you want to submit the new PR, I don't want to take credit @karthink

I think this should be part of #9, which is an important fix, so please go ahead. I'm working on improving macrursors' performance  for now.

**Comment by bscuron** [comment]
Symbols work as intended. Here is a video:

https://user-images.githubusercontent.com/29784485/221433983-c4194037-8ef0-4bf2-a100-041f8978bd9e.mov

I am putting together a new PR now. It seems like I cannot add to #9, since it is already merged into main.

**Comment by bscuron** [comment]
Closing with #11 being created
