### ISSUE TITLE
Mark regexp matches

### ISSUE THREAD

**Issue by bscuron** [corytertel/macrursors#2]
Would it be possible to have a way to mark regexp matches? I modified some code from meow which does similar. 

```emacs lisp

(defun macrursors-mark-regexp nil
  "Mark each regexp match"
  (interactive)
  (let (match)
    (setq match (read-regexp "Mark regexp: "))
    (when (region-active-p)
      (narrow-to-region (region-beginning) (region-end)))
    (let ((orig-end (region-end))
          (orig-beg (region-beginning)))
      (save-mark-and-excursion
        (goto-char (point-min))
        (let ((case-fold-search nil))
          (while (re-search-forward match nil t)
            (unless (or (= orig-end (point))
                        (= orig-beg (point)))
              (let ((match (match-data)))
                (macrursors--add-overlay-at-point (car match))
                )))))
      (goto-char (overlay-start (car macrursors--overlays)))
      (delete-overlay (car macrursors--overlays))
      (setq macrursors--overlays (cdr macrursors--overlays))
      (widen)
      (deactivate-mark)
      (macrursors-start))))
```

I am not too familiar with elisp. This code fails when there are no matching patterns and when the pattern is `^` or `$`. I also tried to have it only mark matches in the region if it is activated.

**Comment by karthink** [comment]
@bscuron Do you mean visually marking matches like `iedit` does?

https://user-images.githubusercontent.com/8607532/217676033-b183e2ae-3f79-4570-97ee-cc6274b0d748.mp4

I'm not sure it makes sense to add this to macrursors.

Or perhaps you mean just placing cursors at the end of matches? My opinion: I'm not a fan of adding loads of commands to packages -- makes them harder to use and maintain. I like to compose simpler commands to do what I want instead. For example, I'm marking regexps from isearch instead: it's as fast as a dedicated command, I have all the isearch bonus features* at hand, and I don't have to remember that `macrursors-mark-regexp` exists and memorize another keybinding. Example: 

https://user-images.githubusercontent.com/8607532/217677992-01283b0a-0226-47b1-a681-16a3473d5509.mp4

(* Such as isearch's live overlays showing matches, and goodies like `isearch-lax-whitespace`, which is amazing.)

**Comment by bscuron** [comment]
> Or perhaps you mean just placing cursors at the end of matches?

This is exactly what I mean. Are you using a special function to achieve the functionality of placing a cursor at each isearch match? If so, would you be open to sharing that function?

**Comment by karthink** [comment]
> > Or perhaps you mean just placing cursors at the end of matches?
> 
> This is exactly what I mean. Are you using a special function to achieve the functionality of placing a cursor at each isearch match? If so, would you be open to sharing that function?

```emacs-lisp
(defun macrursors-mark-from-isearch (&optional arg)
  "Make macrursors from the last search string."
  (interactive "P")
  (or isearch-success (user-error "Nothing to match."))
  (let* ((regexp
          (cond
           ((functionp isearch-regexp-function)
            (funcall isearch-regexp-function isearch-string))
           (isearch-regexp-function (word-search-regexp isearch-string))
           (isearch-regexp isearch-string)
           (t (regexp-quote isearch-string))))
         (selection-p (macrursors--inside-secondary-selection))
         (search-start (if selection-p
		           (overlay-start mouse-secondary-overlay)
                         0))
         (search-end (and selection-p
                          (overlay-end mouse-secondary-overlay)))
         orig-point)
    (goto-char (max (point) isearch-other-end))
    (isearch-exit)
    (setq orig-point (point))
    (save-excursion
      (goto-char search-start)
      (macrursors--mark-all-instances-of regexp orig-point search-end))
    (macrursors-start)))
```

**Comment by bscuron** [comment]
Great! Thank you!

**Comment by bscuron** [comment]
Hi sorry to bother you again @karthink . Do you have any idea the isearch regexp matches do not get marked in this case? Here is a video:

https://user-images.githubusercontent.com/29784485/218265348-57288bd7-87a0-49d5-bb9e-06949c754b72.mov

Thank you for any feedback.

**Comment by karthink** [comment]
Hi @bscuron,

I'm not able to reproduce this bug:
 
https://user-images.githubusercontent.com/8607532/218269183-b7238e28-96b1-48b9-a10a-e6cdb8bf64d6.mp4

However the cursor at the end of the buffer (next to `e`) is invisible, which I'll look into. 

Puzzling!

**Comment by bscuron** [comment]
Interesting. Ill try with a clean config. Might have something to do with my isearch setup.

```emacs lisp
(setq search-whitespace-regexp ".*")
(setq isearch-lax-whitespace t)
(setq isearch-regexp-lax-whitespace nil)
```

Thanks @karthink

**Comment by bscuron** [comment]
Hi @karthink. I tried again with a minimal config:

```emacs lisp
;; Multiple cursors
(add-to-list 'load-path "~/dotfiles/emacs/lisp/macrursors")
(load-library "macrursors")

;; Mark isearch
(defun macrursors-mark-from-isearch (&optional arg)
  "Make macrursors from the last search string."
  (interactive "P")
  (or isearch-success (user-error "Nothing to match."))
  (let* ((regexp
          (cond
           ((functionp isearch-regexp-function)
            (funcall isearch-regexp-function isearch-string))
           (isearch-regexp-function (word-search-regexp isearch-string))
           (isearch-regexp isearch-string)
           (t (regexp-quote isearch-string))))
         (selection-p (macrursors--inside-secondary-selection))
         (search-start (if selection-p
		           (overlay-start mouse-secondary-overlay)
                         0))
         (search-end (and selection-p
                          (overlay-end mouse-secondary-overlay)))
         orig-point)
    (goto-char (max (point) isearch-other-end))
    (isearch-exit)
    (setq orig-point (point))
    (save-excursion
      (goto-char search-start)
      (macrursors--mark-all-instances-of regexp orig-point search-end))
    (macrursors-start)))

;; Bind key
(define-key isearch-mode-map (kbd "C-.") 'macrursors-mark-from-isearch)
```

but I am still only getting the first match. I will continue to try to figure this out. Emacs version: `GNU Emacs 28.2 (build 1, x86_64-apple-darwin18.7.0, NS appkit-1671.60 Version 10.14.6 (Build 18G95)) of 2022-09-12`

**Comment by karthink** [comment]
Okay, this happens because `macrursors--mark-all-instances-of` uses `search-forward` instead of `re-search-forward`. I'm a few commits ahead in my fork, where this is fixed, so I didn't observe this issue. You can change it to `re-search-forward` for now, or switch to [my fork](https://github.com/karthink/macrursors/tree/all-features) (Be sure to use the `all-features` branch if you do). It has additional fixes and features that I will PR if @corytertel approves, such as marking the symbol at point by default when calling `-mark-next-instance` (see #4), and automatic selection cycling (see #5).

**Comment by bscuron** [comment]
Great! I switched to your fork for now. Regarding #4, if the region is active, will the function still mark the next instance of the region? I like the idea of having the symbol marked if the region is not yet active. If so, I can close my PR #6.

Thank you again @karthink

**Comment by karthink** [comment]
> Great! I switched to your fork for now. Regarding #4, if the region is active, will the function still mark the next instance of the region?

Here's how it works:

- If the region is active, mark next instance of region
- If the region is inactive and there is a symbol at point, mark next instance of symbol
- If there is no symbol at point, do nothing -- for now.

-----

I'm think of adding a cursor to the next/previous line in this case (no active region and no symbol at point), so you can quickly add cursors to a bunch of lines with `mark-next-instance-of` and `mark-previous-instance-of`, but I'm undecided about adding this much "magic" behavior. What do you think?

**Comment by bscuron** [comment]
I would like that functionality a lot! That would cover 99% of my use cases together with the isearch function you provided above. I am going to close my PR #6 since the functionality is covered in your upcoming PR.

Thank you for the help! @karthink

**Comment by karthink** [comment]
> I would like that functionality a lot!

To be clear, the version in my fork already marks the symbol at point if the region is inactive. Did you mean that you would like the functionality where it marks the next/previous line instead if there's no symbol at point?

**Comment by bscuron** [comment]
> > I would like that functionality a lot!
> 
> To be clear, the version in my fork already marks the symbol at point if the region is inactive. Did you mean that you would like the functionality where it marks the next/previous line instead if there's no symbol at point?

Yes, I would like it if it marked the prev/next line if there is no symbol at point. Sorry for the confusion! @karthink

**Comment by karthink** [comment]
All right, I'll add the next/previous line marking to my fork soon. If @corytertel thinks this is useful behavior for the main package I can raise a PR.

**Comment by corytertel** [comment]
I think that the next/previous line would increase intuitiveness. I'm not opposed to adding it to the main package.

**Comment by karthink** [comment]
> I think that the next/previous line would increase intuitiveness.

With the following ordering:

1. If region is active, mark next/prev instance of region
2. If region is inactive and there is a symbol at point, mark next/prev instance of symbol at point
3. If there is no symbol at point, mark next/prev line.

The case I'm concerned about is: There is a symbol at point, but the user wants to mark the next line.  For example, with the cursor `|` at the end of `var1` here:

``` python
var1| = 4
var2 = 5

var3 = var1 + var2
```

The user might very well expect to achieve this result with `mark-next-instance-of`

``` python
var1| = 4
var2| = 5

var3 = var1 + var2
```

but will instead cause this to happen:

``` python
var1| = 4
var2 = 5

var3 = var1| + var2
```

Nevertheless, I can raise a PR -- we can test this behavior for a while without committing to it and see if feels intuitive.  We can always roll it back if needed.

**Comment by karthink** [comment]
@bscuron If you're still using my fork you can switch back to the original now.  Every feature I was working on has been merged, and I'm going to be doing some experimentation that will break things.

**Comment by bscuron** [comment]
> @bscuron If you're still using my fork you can switch back to the original now.  Every feature I was working on has been merged, and I'm going to be doing some experimentation that will break things.
> 

Will do. Thanks for the heads up! @karthink
