### ISSUE TITLE
`macrursors-mark-next-instance-of` moves to end of region when region is selected with `mark-sexp` C-M-SPC

### ISSUE THREAD

**Issue by bscuron** [corytertel/macrursors#4]
When text is selected using C-M-SPC and `macrursors-mark-next-instance-of` is run, the mark and point become the same. This makes it so that `macrursors-mark-next-instance-of` can only be ran once.

I implemented this fix for now that seems to be working:

```emacs lisp

;;;###autoload
(defun macrursors-mark-next-instance-of ()
  (interactive)
  (when defining-kbd-macro (end-kbd-macro))
  (if (use-region-p)
      (progn
	(let ((region (buffer-substring-no-properties (region-beginning)
                                                      (region-end)))
	      (end (and (macrursors--inside-secondary-selection)
                    (overlay-end mouse-secondary-overlay))))
      (when (< (point) (mark))
        (exchange-point-and-mark))
	  (goto-char (region-end))
          (save-excursion
	    (macrursors--mark-next-instance-of region end))
	  (macrursors-start)))
    (error "No region active")))
```

The only difference is the two lines:
```emacs lisp
      (when (< (point) (mark))
        (exchange-point-and-mark))
```

I am not good at emacs lisp so I am not sure if this is the best way to do this.

Here is a video of the problem:

https://user-images.githubusercontent.com/29784485/217713410-68408625-464f-493f-b5de-95f8e6b0f17c.mov

**Comment by karthink** [comment]
Oops, my bad, sorry. I wrote this version of the `mark-*-instance-of` commands. You can safely get rid of the `(goto-char (region-end))` statement as well.

BTW I'm working on a new version of this command that makes what you're trying to do (`C-M-SPC`, then `mark-next-instance`) automatic. I'll add an update here soon.

**Comment by karthink** [comment]
Update: selecting symbol at point by default:

https://user-images.githubusercontent.com/8607532/218279076-b87fa33b-5ff1-43c2-a61c-19c3a170f650.mp4

**Comment by bscuron** [comment]
#4 Fixed by @karthink in coming PR!
